### ISSUE TITLE
ESP32 restarts after a while when using dual core 

### ISSUE THREAD

**Issue by Nakul93** [SensorsIot/ESP32-Dual-Core#1]
I am trying to read 2 different sensor values and publishing them to an mqtt server from 2 different cores.
It starts off nicely but after some time I get this following error and the core1 reboots. So I am get data from core1 but core0 doesn't work.

CORRUPT HEAP: Bad head at 0x3ffe84cc. Expected 0xabba1234 got 0x3ffffff8
assertion "head != NULL" failed: file "/Users/ficeto/Desktop/ESP32/ESP32/esp-idf-public/components/heap/./multi_heap_poisoning.c", line 199, function: multi_heap_free
abort() was called at PC 0x400d87af on core 1

Backtrace: 0x40087f20:0x3ffdd570 0x4008801f:0x3ffdd590 0x400d87af:0x3ffdd5b0 0x40087c49:0x3ffdd5e0 0x40083d6e:0x3ffdd600 0x400842f9:0x3ffdd620 0x4000bec7:0x3ffdd640 0x400f204e:0x3ffdd660 0x400d33ac:0x3ffdd680 0x400d3175:0x3ffdd6a0 0x400d3221:0x3ffdd6c0 0x401424ea:0x3ffdd6e0 0x400d393b:0x3ffdd700 0x400d39a1:0x3ffdd720 0x400d3ac8:0x3ffdd740 0x400d1db5:0x3ffdd790

Rebooting...

**Comment by Jaystings** [comment]
How long did it take for this to happen?
