### ISSUE TITLE
[Question] How to prevent "Task watchdog got triggered." message

### ISSUE THREAD

**Issue by OllisGit** [SensorsIot/ESP32-Dual-Core#3]
First: Thanks a lot for your effort creating such a huge pool of information about ESP!!!

I used the Multi-Core feature for a main-loop (reading/sending sensor-data) and a LED-Status loop.
The LED-Loop (run on CPU#0)  controls all my status LEDs which use JLed-Library and if sending take some time (run on CPU #1), the status leds are not affected. 

But the message  "Task watchdog got triggered. The following tasks did not reset..."   (you also mentioned in your video) is realy annoying.

Do you have a solution, how to prevent such message? Change logLevel or do some other magic?

Thx, in advance
Olli

**Comment by SensorsIot** [comment]
No, I have no solution.
